#!/bin/sh
#EDMFILES=~diamond/R3.13.4/prod/support/edm_config/1-0/setup
#export EDMFILES
EDMDATAFILES=../digitelMpcApp/opi/edl:../digitelMpcApp/opi/symbol:.
export EDMDATAFILES
export EPICS_CA_SERVER_PORT=6064
export EPICS_CA_REPEATER_PORT=6065
edm -x -eolc digitelMpc-launch.edl &
